# Generated by Django 5.0.6 on 2024-07-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0002_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidades',
            field=models.ManyToManyField(to='medicitas.especialidad'),
        ),
    ]
