# Generated by Django 5.0.6 on 2024-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0004_rename_apellido_medico_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='es_covid',
            field=models.BooleanField(default=False),
        ),
    ]
