# Generated by Django 5.0.6 on 2024-07-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0005_citamedica_es_covid'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
        migrations.AddField(
            model_name='medico',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], default='masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], default='masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='personal',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
        migrations.AddField(
            model_name='personal',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], default='masculino', max_length=10),
        ),
    ]
