# Generated by Django 5.0.6 on 2024-07-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0007_rename_especialidades_medico_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ManyToManyField(related_name='medicos', to='medicitas.especialidad'),
        ),
    ]
