# Generated by Django 5.0.6 on 2024-07-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0009_remove_medico_especialidad_medico_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citamedica',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='citamedica',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicitas.especialidad'),
        ),
    ]
