# Generated by Django 5.0.6 on 2024-07-05 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0010_remove_citamedica_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='num_identificacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
