# Generated by Django 5.0.6 on 2024-07-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0012_historialmedico_estatura_historialmedico_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='unidad_estatura',
            field=models.CharField(default='metros', max_length=10),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='unidad_peso',
            field=models.CharField(default='libras', max_length=10),
        ),
    ]
