# Generated by Django 5.0.6 on 2024-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0013_historialmedico_unidad_estatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='unidad_estatura',
            field=models.CharField(choices=[('Metros', 'Metros'), ('Pulgadas', 'Pulgadas')], default='metro', max_length=10),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='unidad_peso',
            field=models.CharField(choices=[('Libras', 'Libras'), ('Kilos', 'Kilos')], default='libras', max_length=10),
        ),
    ]
