# Generated by Django 5.0.6 on 2024-07-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0014_alter_historialmedico_unidad_estatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
