# Generated by Django 5.0.6 on 2024-07-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0015_especialidad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='es_influenza',
            field=models.BooleanField(default=False),
        ),
    ]
