# Generated by Django 5.0.6 on 2024-07-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0016_citamedica_es_influenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='citas',
            field=models.ManyToManyField(limit_choices_to={'paciente': models.F('paciente')}, related_name='historial_medico', to='medicitas.citamedica'),
        ),
    ]
