# Generated by Django 5.0.6 on 2024-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0019_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='horario_atencion',
            field=models.CharField(choices=[('08:00-12:00', '08:00 AM - 12:00 PM'), ('14:00-18:00', '02:00 PM - 06:00 PM'), ('08:00-18:00', '08:00 AM - 06:00 PM'), ('10:00-14:00', '10:00 AM - 02:00 PM')], default='08:00-12:00', max_length=20),
        ),
    ]
