# Generated by Django 5.0.6 on 2024-12-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0022_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='codigo_secreto',
            field=models.CharField(default='valor_por_defecto', max_length=100),
        ),
    ]
