# Generated by Django 5.0.6 on 2024-12-26 14:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0023_administrador_codigo_secreto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='codigo_secreto',
        ),
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.EmailField(default='admin@dominio.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='num_documento',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números en el número de documento', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], default='masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de teléfono inválido', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='tipo_documento',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], default='cedula', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
