# Generated by Django 5.0.6 on 2024-12-26 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0026_alter_administrador_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
        migrations.AddField(
            model_name='administrador',
            name='codigo_secreto',
            field=models.CharField(default='valor_por_defecto', max_length=100),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='num_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otros', 'Otros')], max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='tipo_documento',
            field=models.CharField(choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte')], max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
