# Generated by Django 5.0.6 on 2024-12-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0027_remove_administrador_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
