# Generated by Django 5.0.6 on 2025-01-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0029_remove_administrador_codigo_secreto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='user',
            new_name='usuario',
        ),
    ]
