# Generated by Django 5.0.6 on 2025-01-20 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0030_rename_user_administrador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='historial_medico',
        ),
        migrations.AddField(
            model_name='receta',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='medicitas.paciente'),
        ),
    ]
