# Generated by Django 5.0.6 on 2025-02-02 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0032_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('tipo_sangre', models.CharField(max_length=3)),
                ('ritmo_cardiaco', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('presion_arterial', models.CharField(max_length=7)),
                ('enfermedades', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicitas.paciente')),
            ],
        ),
    ]
