# Generated by Django 5.0.6 on 2025-02-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0033_estadopaciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
