# Generated by Django 5.0.6 on 2025-02-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicitas', '0035_emergencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencia',
            name='nivel_conciencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='presion_arterial',
            field=models.IntegerField(),
        ),
    ]
